name: Windows Security Audit CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 (Python linting)
        run: flake8 .

      # --- PowerShell linting starts here ---
      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
        shell: pwsh

      - name: Run PSScriptAnalyzer (PowerShell linting)
        run: |
          $results = Invoke-ScriptAnalyzer -Path ./ -Recurse
          if ($results.Count -gt 0) {
            Write-Host "PSScriptAnalyzer found issues:"
            $results | Format-Table -AutoSize
            exit 1  # fail the workflow
          } else {
            Write-Host "No PowerShell linting issues found."
          }
        shell: pwsh
      # --- PowerShell linting ends here ---

      - name: Run Windows Security Audit
        run: python main.py

      - name: Upload Audit Report
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: results/audit_report.txt
