name: Windows Security Audit Toolkit CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt, skipping dependency installation"
          fi

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 . || true   # don't fail yet, just show warnings

      - name: Run main script
        run: |
          python main.py || echo "main.py did not execute successfully, check logs"
